# Generated by Django 5.1 on 2024-09-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalPrice', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('stock', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('pic1', models.ImageField(upload_to='images/')),
                ('pic2', models.ImageField(upload_to='images/')),
                ('pic3', models.ImageField(upload_to='images/')),
                ('pic4', models.ImageField(upload_to='images/')),
                ('maincat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shukhiannaApp.maincategory')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shukhiannaApp.subcategory')),
            ],
        ),
    ]
