# Generated by Django 5.1 on 2024-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shukhiannaApp', '0003_alter_maincategory_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
