# Generated by Django 5.1 on 2024-09-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shukhiannaApp', '0005_alter_product_pic1_alter_product_pic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
